version: "3.8"
services:
  app1:
    build:  .
    volumes:
      - .:/django
    ports:
      - 8004:8004
    image:  app1:django
    container_name: django_container4
    command: python manage.py runserver 0.0.0.0:8004
    depends_on:
      - db2
  db2:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db2
