version: "3.8"
services:
  app:
    build:  .
    volumes:
      - .:/django
    ports:
      - 8002:8002
    image:  app:django
    container_name: django_container3
    command: python manage.py runserver 0.0.0.0:8002